# Generated by Django 3.0.8 on 2020-07-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_auto_20200722_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='user_image/post'),
        ),
    ]
