# Generated by Django 3.0.8 on 2020-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0006_auto_20200723_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(default='user_image/default/default.jpg', upload_to='user_image/profiles'),
        ),
    ]
