# Generated by Django 3.0.8 on 2020-07-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0010_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['time']},
        ),
    ]
